## Implementing Backpropagation algorithm to train majority function with 3-bits with network of configuration 3x2x2x1

In [1]:
import numpy as np

np.random.seed(9)
import math

In [6]:
def initialize_weights(layers):
    w1 = np.reshape(np.random.rand(layers[1] * layers[2]),(layers[1],layers[2]))
    w2 = np.reshape(np.random.rand(layers[2] * layers[3]),(layers[2], layers[3]))
    w3 = np.reshape(np.random.rand(layers[3] * layers[4]), (layers[3], layers[4]))
    W = {
        1 :w1,
        2 :w2,
        3 :w3,
    }
    b1 = np.reshape(np.zeros(layers[2]),(1, layers[2]))
    b2 = np.reshape(np.zeros(layers[3]),(1, layers[3]))
    b3 = np.reshape(np.zeros(layers[4]),(1, layers[4]))
    b = {
        1 :b1,
        2 :b2,
        3 :b3,
    }
    return W,b


In [3]:
def activation(X, W, b):
    z = np.matmul(X,W) + b
    A = 1/(1 + np.exp(-z))
    return A

In [4]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [42]:
X = np.array([[0,0,0,0,1,1,1,1],[0,0,1,1,0,0,1,1],[0,1,0,1,0,1,0,1]]).T
Y = np.array([0,0,0,1,0,1,1,1]).reshape(8,1)
layers_num = 4
epoch = 2000
alpha = 0.1
layers = {
    1 :3,
    2 :2,
    3 :2,
    4 :1
}
W, b = initialize_weights(layers)
print("Initial Wieghts:")
print("----------------")
print("Layer 1:\n",W[1])
print("\nLayer 2:\n",W[2])
print("\nLayer 3:\n",W[3])

print("\n\nInitial bias:")
print("------------")
print("Layer 1:\n",b[1])
print("\nLayer 2:\n",b[2])
print("\nLayer 3:\n",b[3])


Initial Wieghts:
----------------
Layer 1:
 [[0.31400088 0.87018638]
 [0.98979225 0.5695085 ]
 [0.2227709  0.28580263]]

Layer 2:
 [[0.81812279 0.56102522]
 [0.54239249 0.1495605 ]]

Layer 3:
 [[0.74024486]
 [0.15651551]]


Initial bias:
------------
Layer 1:
 [[0. 0.]]

Layer 2:
 [[0. 0.]]

Layer 3:
 [[0.]]


In [44]:

for i in range(epoch):
    
    #Forward Propagation

    A1 = activation(X, W[1], b[1])
    A2 = activation(A1, W[2], b[2])
    A3 = activation(A2, W[3], b[3])

    error_layer3 = Y - A3
    delta_A3 = error_layer3 * sigmoid_derivative(A3)

    error_layer2 = delta_A3.dot(W[3].T)
    delta_A2 = error_layer2 * sigmoid_derivative(A2)

    error_layer1 = delta_A2.dot(W[2].T)
    delta_A1 = error_layer1 * sigmoid_derivative(A1)

    # Weight and bias update
    W[1] += X.T.dot(delta_A1) * alpha
    b[1] += np.sum(delta_A1, axis = 0, keepdims = True) * alpha

    W[2] += A1.T.dot(delta_A2) * alpha
    b[2] += np.sum(delta_A2, axis = 0, keepdims = True) * alpha

    W[3] += A2.T.dot(delta_A3) * alpha
    b[3] += np.sum(delta_A3, axis = 0, keepdims = True) * alpha

print("Weights of layer 1:\n",W[1])
print("Bias of layer 1:\n",b[1])

print("\n\nWeight of layer 2:\n",W[2])
print("Bias of layer 2:\n",b[2])

print("\n\nWeights of layer 3:\n",W[3])
print("Bias of layer 3:\n",b[3])

print("\n\nFinal Output:\n",A3.T)


Weights of layer 1:
 [[2.3210733  2.04151024]
 [2.40631524 1.93845238]
 [2.37839745 1.97325733]]
Bias of layer 1:
 [[-3.57531509 -2.99272636]]


Weight of layer 2:
 [[4.79318884 1.29615747]
 [3.80816638 0.75190601]]
Bias of layer 2:
 [[-4.28648351 -0.78660656]]


Weights of layer 3:
 [[7.90165965]
 [0.88448928]]
Bias of layer 3:
 [[-4.33685842]]


Final Output:
 [[0.01983196 0.04133867 0.04130508 0.96524137 0.04140786 0.96531813
  0.9652925  0.98368185]]
